server:
  port: 9011


spring:
  jackson:
    # 全局配置 json 时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://192.168.17.131:3306/launch?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.mingyang.bootlaunch: INFO # 日志级别
  config: classpath:logback-spring.xml